### PR TITLE
Conversions

### PR DESCRIPTION
**Pull request by SMITHsharon**
stuck : / 
event handlers for both <onkeyup> for Enter key, and <onclick> for radio buttons. 
Searches turn up conflicting, and therefore, confusing things to try. 
So I have a mess.

### CODE REVIEW

**Comment by justinal64** [comment]
@SMITHsharon  Lets work through this project in the morning.

**Comment by SMITHsharon** [comment]
👍

**Comment by SMITHsharon** [comment]
@justinal64 :: temp converter is done. Event handlers are working correctly, and I believe all functionality is correct;)

**Comment by justinal64** [comment]
@SMITHsharon  Nice job your code is very readable and the comments above the methods is a great touch. 👍

**Pull request merged**
